#' csv file of sample data
#'
#' @format csv file with 5 entries
#' \describe{
#'     \item{title}{any kind of professional name}
#'     \item{first}{given or first name}
#'     \item{second}{family or surname}
#'     \item{role}{organiser, speaker or delegate}
#'     \item{email}{contact details}
#'     \item{affiliation}{organisation}
#'     \item{include_gender_pronouns}{YES or NO}
#'     \item{gender_pronouns}{can be a variety}

#' }
#' @return A csv with 5 rows and 8 variables
#' @source generated by hand on Oct 15 2020
"badgeR_sample_data.csv"

NULL
